apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-visualizer
  labels:
    app: log-visualizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-visualizer
  template:
    metadata:
      labels:
        app: log-visualizer
    spec:
      containers:
      - name: log-visualizer
        image: gcr.io/helical-ion-441012-v0/log-visualizer:1.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "75m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: log-visualizer-loadbalancer
spec:
  selector:
    app: log-visualizer
  ports:
    - protocol: TCP
      port: 4200          # Puerto público expuesto
      targetPort: 3000    # Puerto interno del contenedor
  type: LoadBalancer