services:
  ftp-server:
    image: fauria/vsftpd
    ports:
      - "21:21"               # Puerto principal de FTP
      - "21100-21110:21100-21110"  # Rango de puertos pasivos
    environment:
      FTP_USER: "user"
      FTP_PASS: "password"
      PASV_ADDRESS: "127.0.0.1"     # O la dirección IP del host
      PASV_MIN_PORT: "21100"
      PASV_MAX_PORT: "21110"
    volumes:
      - ./ftp_data:/home/vsftpd/user

  sftp-server:
    image: atmoz/sftp
    ports:
      - "22:22"
    volumes:
      - ./sftp_data:/home/user
    environment:
      SFTP_USERS: "user:password:1001"

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress_data:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql

  vulnerable-microservice:
    build:
      context: ./product-service/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
