apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-digital-twin-httpd-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-digital-twin-httpd-server
  template:
    metadata:
      labels:
        app: my-digital-twin-httpd-server
        group: shared-group
    spec:
      containers:
      - name: my-digital-twin-httpd-container
        image: gcr.io/helical-ion-441012-v0/httpd:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"

