apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp-server
  template:
    metadata:
      labels:
        app: ftp-server
    spec:
      containers:
      - name: ftp-server
        image: fauria/vsftpd
        ports:
        - containerPort: 21
        env:
        - name: FTP_USER
          value: "user"
        - name: FTP_PASS
          value: "password"
        - name: PASV_ADDRESS
          value: "127.0.0.1"
        - name: PASV_MIN_PORT
          value: "21100"
        - name: PASV_MAX_PORT
          value: "21110"
        volumeMounts:
        - mountPath: /home/vsftpd/user
          name: ftp-data
        resources:
          requests:
            memory: "512Mi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "2"  
      volumes:
      - name: ftp-data
        hostPath:
          path: /mnt/ftp_data
---
apiVersion: v1
kind: Service
metadata:
  name: ftp-server
spec:
  selector:
    app: ftp-server
  ports:
    - protocol: TCP
      port: 21
      targetPort: 21
  type: NodePort