apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    group: shared-group # Apunta a todos los servicios con etiquetas compartidas
  ports:
    - name: ftp
      protocol: TCP
      port: 21
      targetPort: 21
    - name: sftp
      protocol: TCP
      port: 22
      targetPort: 22
    - name: vuln-ms
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: httpd
      protocol: TCP
      port: 80
      targetPort: 80
    - name: passive-ports1
      port: 21100
      targetPort: 21100
    - name: passive-ports2
      port: 21110
      targetPort: 21110
    - name: fluentd
      port: 9880
      targetPort: 9880