apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-microservice
  template:
    metadata:
      labels:
        app: vulnerable-microservice
    spec:
      containers:
      - name: vulnerable-microservice
        image: vulnerable-ms
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: development
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: vulnerable-microservice
spec:
  selector:
    app: vulnerable-microservice
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
