apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-microservice
  template:
    metadata:
      labels:
        app: vulnerable-microservice
        group: shared-group
    spec:
      containers:
      - name: vulnerable-microservice
        image: ms-vuln-2:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: development
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
