apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-digital-twin-sftp-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-digital-twin-sftp-server
  template:
    metadata:
      labels:
        app: my-digital-twin-sftp-server
        group: shared-group
    spec:
      containers:
      - name: my-digital-twin-sftp-server-container
        image: atmoz/sftp
        ports:
        - containerPort: 22
        env:
        - name: SFTP_USERS
          value: "user:password:1001"
        volumeMounts:
        - mountPath: /home/user
          name: sftp-data
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
      volumes:
      - name: sftp-data
        persistentVolumeClaim:
          claimName: my-digital-twin-sftp-volume-claim

