
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-digital-twin-ftp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-digital-twin-ftp-server
  template:
    metadata:
      labels:
        app: my-digital-twin-ftp-server
        group: shared-group
    spec:
      volumes:
      - name: my-digital-twin-ftp-storage
        persistentVolumeClaim:
          claimName: my-digital-twin-ftp-volume-claim
      containers:
      - name: my-digital-twin-ftp-container
        image: fauria/vsftpd
        ports:
        - containerPort: 21
          protocol: TCP
          name: "ftp-server-port"
        volumeMounts:
        - mountPath: "/home/vsftpd"
          name: my-digital-twin-ftp-storage
        env:
        - name: FTP_USER
          value: "user"
        - name: FTP_PASS
          value: "password"
        #- name: PASV_ADDRESS
        #  value: "127.0.0.1"
        #- name: PASV_MIN_PORT
        #  value: "21100"
        #- name: PASV_MAX_PORT
        #  value: "21110"
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"