
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-digital-twin-ftp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-digital-twin-ftp-server
  template:
    metadata:
      labels:
        app: my-digital-twin-ftp-server
        group: shared-group
    spec:
      volumes:
      - name: my-digital-twin-ftp-storage
        persistentVolumeClaim:
          claimName: my-digital-twin-ftp-volume-claim
      containers:
      - name: my-digital-twin-ftp-container
        image: stilliard/pure-ftpd
        ports:
        - containerPort: 21
          name: ftp-port
        - containerPort: 21100
          name: pasv-min-port
        - containerPort: 21110
          name: pasv-max-port
        env:
        - name: FTP_USER_NAME
          value: "mydigitaltwinuser"
        - name: FTP_USER_PASS
          value: "sevensectorunir"
        volumeMounts:
        - name: my-digital-twin-ftp-storage
          mountPath: "/home/ftpusers"
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
