apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: default
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/containers/fluentd.pos
      tag kubernetes.*
      <parse>
        @type json
      </parse>
    </source>

    <match kubernetes.**>
      @type http
      endpoint http://34.65.84.23:9880
      http_method post
      serializer json
    </match>
